version: '3'
services:
  # nginx:
  #   restart: always
  #   build: containers/nginx
  #   # container_name: nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - api

  api:
    restart: always
    build: .
    container_name: api
    hostname: api
    ports:
      - "8080:8080"
    volumes:
      - ./api/:/myapp
    working_dir: /myapp
    # command: [sh, -c, npm install && npm start]
    command: [sh, -c, npm start]
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
  client:
    restart: always
    build: .
    container_name: client
    hostname: client
    ports:
      - "4200:4200"
      - "9876:9876"
    volumes:
      - ./client:/myapp
    working_dir: /myapp
    command: [sh, -c, npm start]
    environment:
      - NODE_ENV=development

  mongodb:
    # restart: always
    image: mongo:latest
    # container_name: mongodb
    environment:
      -  'MONGODB_USER=user' 
      -  'MONGODB_PASS=password!'
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    # command: [sh, -c, rm /data/db/mongod.lock && mongod --smallfiles]
    command: mongod --smallfiles
